# SPDX-FileCopyrightText: 2021 Scott Shawcroft for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Failure help text

on:
  workflow_run:
    workflows: ["Build CI"]
    types:
      - completed

jobs:
  post-help:
    runs-on: ubuntu-latest
    {% raw %}if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'pull_request' }}{% endraw %}
    steps:
    - name: Post comment to help
      uses: adafruit/circuitpython-action-library-ci-failed@v1
